services:
  app:
    image: node:20-alpine
    container_name: line-oa
    working_dir: /app
    volumes:
      - .:/app
    # Viteのデフォルトポート(5173)とFirebase(5000, 9005)を開ける
    ports:
      - "5173:5173"
      - "5000:5000"
      - "9005:9005"
    # コンテナを起動し続ける設定
    command: tail -f /dev/null